# Generated by Django 2.2.2 on 2019-06-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0005_auto_20190619_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
