# Generated by Django 2.2.2 on 2019-06-18 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0006_cart_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='qty',
        ),
    ]
