# Generated by Django 2.2.2 on 2019-06-21 19:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeapp', '0008_oreder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oreder',
            new_name='Order',
        ),
    ]
